-- Field Service Calculator Database Schema
-- Create database (uncomment if needed)
-- CREATE DATABASE field_service_calculator;
-- USE field_service_calculator;

-- Drop tables if they exist (for clean install)
DROP TABLE IF EXISTS calculations;
DROP TABLE IF EXISTS users;

-- Create users table
CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role ENUM('tech', 'admin') NOT NULL,
    is_active BOOLEAN DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_username (username),
    INDEX idx_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create calculations table
CREATE TABLE calculations (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    service_type ENUM('Residential', 'Commercial') NOT NULL,
    material_cost DECIMAL(10,2) NOT NULL,
    material_markup_percent DECIMAL(5,2) NOT NULL,
    material_charge DECIMAL(10,2) NOT NULL,
    labor_category VARCHAR(50) NOT NULL,
    minutes INT NOT NULL,
    labor_rate DECIMAL(10,2) NOT NULL,
    labor_charge DECIMAL(10,2) NOT NULL,
    include_tax BOOLEAN DEFAULT 0,
    tax_amount DECIMAL(10,2) DEFAULT 0.00,
    total_amount DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
    INDEX idx_user_created (user_id, created_at),
    INDEX idx_created_at (created_at),
    INDEX idx_service_type (service_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert default users
-- Note: These passwords are hashed versions of:
-- admin: admin123
-- tech1: tech123
-- tech2: tech123
-- In production, these should be changed immediately

-- Admin user (password: admin123)
INSERT INTO users (username, email, password, role, is_active) VALUES 
('admin', 'admin@fieldservice.com', '$2y$12$PanhPgD/PtQIFrWAtBtb3uZ.U6qjwksJfbALMDDMkMYHhMbLnpheq', 'admin', 1);

-- Tech users (password: tech123)
INSERT INTO users (username, email, password, role, is_active) VALUES 
('tech1', 'tech1@fieldservice.com', '$2y$12$.GuvBaxT/ZoRDrxST8WPzetNLHGyjog1/B7TQ7OZziTy903MbgjpS', 'tech', 1),
('tech2', 'tech2@fieldservice.com', '$2y$12$.GuvBaxT/ZoRDrxST8WPzetNLHGyjog1/B7TQ7OZziTy903MbgjpS', 'tech', 1);

-- Note: The actual password hashes will be generated by PHP and updated in this file
-- Or you can run these PHP commands to generate the hashes:
-- echo password_hash('admin123', PASSWORD_DEFAULT);
-- echo password_hash('tech123', PASSWORD_DEFAULT);